"""Idem's optional local web GUI, built with Streamlit.

Launch with `idem gui` (requires `pip install idem-check[gui]`).

Design note: this is a thin front end over the exact same functions the
CLI uses (idem.config, idem.runner, idem.audit_log, idem.target) — there
is no separate GUI-only run logic, so a report generated here is
byte-for-byte identical to one generated by `idem run`. The YAML file
stays the real, auditable source of truth; this just gives a friendlier
way to edit it, run it, and read the results.

This app is meant for local, single-user use (like running any other
dev tool on your own machine). It has no authentication — do not expose
it on a public network without adding your own auth in front of it.
Credentials entered here live only in this process's environment
variables for the lifetime of the session; they are never written to
disk.
"""

from __future__ import annotations

import importlib.resources
import os
import re
import tempfile
from pathlib import Path

import streamlit as st
import yaml

from idem.audit_log import append_jsonl, write_markdown_report
from idem.config import Config, ModelConfig, Question, validate_raw_config
from idem.runner import run_questions
from idem.target import TargetError, create_target

_ENV_VAR_PATTERN = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")


def _load_default_yaml() -> str:
    return importlib.resources.files("idem.templates").joinpath("golden_set.yaml").read_text()


def _find_env_vars(text: str) -> list[str]:
    """Find every ${VAR_NAME} reference in the YAML text (e.g. inside a
    custom endpoint's headers), so the GUI can prompt for exactly those.
    """
    return sorted(set(_ENV_VAR_PATTERN.findall(text)))


def _build_config(raw: dict) -> Config:
    raw_model = raw["model"]
    model = ModelConfig(
        provider=raw_model["provider"],
        model_id=str(raw_model["model_id"]),
        base_url=raw_model.get("base_url"),
        endpoint=raw_model.get("endpoint"),
        system_prompt=raw_model.get("system_prompt"),
    )
    questions = [Question(id=q["id"], prompt=q["prompt"], checks=q["checks"]) for q in raw["questions"]]
    return Config(model=model, questions=questions)


def _render_validation_errors(errors: list[str]) -> None:
    st.error(f"{len(errors)} problem(s) found:")
    for error in errors:
        st.markdown(f"- {error}")


def main() -> None:
    st.set_page_config(page_title="Idem", page_icon="🔁", layout="wide")
    st.title("🔁 Idem")
    st.caption(
        "Deterministic drift detection for LLM APIs — edit, validate, and run a golden set. "
        "Local, single-user tool; not meant to be exposed on a public network."
    )

    if "yaml_text" not in st.session_state:
        st.session_state.yaml_text = _load_default_yaml()

    col_editor, col_results = st.columns(2)

    with col_editor:
        st.subheader("Golden set (YAML)")

        uploaded = st.file_uploader("Load an existing golden_set.yaml", type=["yaml", "yml"])
        if uploaded is not None:
            st.session_state.yaml_text = uploaded.getvalue().decode("utf-8")

        st.session_state.yaml_text = st.text_area(
            "golden set yaml",
            value=st.session_state.yaml_text,
            height=480,
            label_visibility="collapsed",
        )

        st.download_button(
            "Download this YAML",
            data=st.session_state.yaml_text,
            file_name="golden_set.yaml",
            mime="text/yaml",
        )

        st.divider()
        st.subheader("Credentials for this run")
        st.caption("Kept only in memory for this session — never written to disk.")

        provider_match = re.search(r"provider:\s*(\w+)", st.session_state.yaml_text)
        provider = provider_match.group(1) if provider_match else None

        env_overrides: dict[str, str] = {}
        if provider == "openai":
            env_overrides["OPENAI_API_KEY"] = st.text_input("OPENAI_API_KEY", type="password")
        elif provider == "anthropic":
            env_overrides["ANTHROPIC_API_KEY"] = st.text_input("ANTHROPIC_API_KEY", type="password")
        elif provider == "custom":
            for var in _find_env_vars(st.session_state.yaml_text):
                env_overrides[var] = st.text_input(var, type="password")

        validate_col, run_col = st.columns(2)
        validate_clicked = validate_col.button("Validate", use_container_width=True)
        run_clicked = run_col.button("Run", type="primary", use_container_width=True)

    with col_results:
        st.subheader("Results")

        if not validate_clicked and not run_clicked:
            st.info("Click **Validate** to check your YAML, or **Run** to call the model and check its answers.")

        if validate_clicked:
            try:
                raw = yaml.safe_load(st.session_state.yaml_text)
            except yaml.YAMLError as exc:
                st.error(f"Invalid YAML syntax: {exc}")
            else:
                errors = validate_raw_config(raw)
                if errors:
                    _render_validation_errors(errors)
                else:
                    st.success("Config is valid.")

        if run_clicked:
            try:
                raw = yaml.safe_load(st.session_state.yaml_text)
            except yaml.YAMLError as exc:
                st.error(f"Invalid YAML syntax: {exc}")
                return

            errors = validate_raw_config(raw)
            if errors:
                st.error("Config is invalid — fix these first:")
                _render_validation_errors(errors)
                return

            for key, value in env_overrides.items():
                if value:
                    os.environ[key] = value

            config = _build_config(raw)

            try:
                target = create_target(config.model)
            except TargetError as exc:
                st.error(str(exc))
                return

            progress = st.progress(0.0, text="Starting...")
            seen = 0

            def on_result(result):
                nonlocal seen
                seen += 1
                progress.progress(seen / len(config.questions), text=f"Checked '{result.question_id}'")

            with st.spinner("Calling the model..."):
                results, had_runtime_error = run_questions(config, target, on_result=on_result)
            progress.empty()

            passed = sum(1 for r in results if r.overall_passed)
            failed = len(results) - passed
            if had_runtime_error:
                st.warning("Run finished with runtime errors — see details below.")
            elif failed == 0:
                st.success(f"All {passed} question(s) passed.")
            else:
                st.error(f"{failed} of {len(results)} question(s) failed.")

            for result in results:
                icon = "✅" if result.overall_passed else "❌"
                with st.expander(f"{icon} {result.question_id}", expanded=not result.overall_passed):
                    if result.error:
                        st.error(result.error)
                        continue
                    st.markdown(f"**Prompt:** {result.prompt}")
                    st.markdown("**Response:**")
                    st.markdown(f"> {result.raw_response}")
                    for check_result, check_config in zip(result.check_results, result.check_configs):
                        mark = "✅" if check_result.passed else "❌"
                        st.markdown(f"{mark} `{check_result.check_type}` — {check_result.detail}")

            with tempfile.TemporaryDirectory() as tmpdir:
                tmp_path = Path(tmpdir)
                jsonl_path = tmp_path / "audit_log.jsonl"
                report_path = tmp_path / "report.md"
                for result in results:
                    append_jsonl(jsonl_path, result.to_record())
                write_markdown_report(report_path, results)

                dl_col1, dl_col2 = st.columns(2)
                dl_col1.download_button(
                    "Download report.md",
                    data=report_path.read_text(),
                    file_name="report.md",
                    mime="text/markdown",
                )
                dl_col2.download_button(
                    "Download audit_log.jsonl",
                    data=jsonl_path.read_text(),
                    file_name="audit_log.jsonl",
                    mime="application/jsonl",
                )


main()
